### PR TITLE
Highlights

### PR DESCRIPTION
**Pull request by MulugetaTesfay**

### CODE REVIEW

**Comment by MulugetaTesfay** [comment]
I tried to solve the conflict but, something is wrong which i couldn't understand.

**Comment by MulugetaTesfay** [comment]
Conflicting files
css/highlights.css
css/top-menu.css
index.html

**Comment by hphoeksma** [comment]
@MulugetaTesfay remove the changes from the top-menu.css from this PR. They should not be in here.

**Comment by hphoeksma** [comment]
For the index.html file as well: make changes only within the section with class highlights.

**Pull request merged**
